# Config file for pipeline_split_by_index.py

## general options

# Copyright statement
copyright: cribbslab (2021)

FP: AAGCAGTGGTATCAACGCAGAGTGAAT
RP: GTACTCTGCGTTGATACCACTGCTT

indexes:
  - AAATTTGGGCCC
  - TTTCCCAAAGGG
  - GGGAAACCCTTT
  - CCCGGGTTTAAA
  - AAACCCGGGAAA
  - TTTGGGAAATTT
  - GGGTTTCCCGGG
  - CCCAAATTTCCC
  - AAAGGGAAAGGG
  - TTTAAATTTAAA
  - GGGCCCGGGCCC
  - CCCTTTCCCTTT

## edit distance for primer matching
error: 0.3
split: 4000000

job_options: -t 18:00:00

