name: Test Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install biopython

    - name: Run script with default parameters
      run: |
        python script_name.py test_data.fastq.gz output_reads.fastq

    - name: Run script with custom primer
      run: |
        python script_name.py test_data.fastq.gz output_reads_custom.fastq -p NEWPRIMER

    - name: Run script with custom indexes
      run: |
        python script_name.py test_data.fastq.gz output_reads_custom_indexes.fastq -i AAATTTGGGCCC:1 TTTCCCAAAGGG:2

    - name: Check output file
      run: |
        test -s output_reads.fastq && echo "Output file is not empty"
        test -s output_reads_custom.fastq && echo "Output file with custom primer is not empty"
        test -s output_reads_custom_indexes.fastq && echo "Output file with custom indexes is not empty"
