name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest

    - name: Run tests
      run: |
        pytest tests/

    - name: Run integration test
      run: |
        mkdir -p output
        split_fastqcats tests/test.fastq.gz \
          --output-dir output \
          --processed-output processed.fastq \
          --lowqual-output lowqual.fastq \
          --bin-output binned.fastq \
          --stats-output stats.txt

    - name: Check output files
      run: |
        for file in output/*.fastq; do
          if [ -s "$file" ]; then
            echo "$file exists and is not empty"
          else
            echo "$file is empty or missing"
            exit 1
          fi
        done
        if [ -s "output/stats.txt" ]; then
          echo "Stats file exists and is not empty"
        else
          echo "Stats file is empty or missing"
          exit 1
        fi
