name: Test Script with Default Parameters

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install biopython

    - name: Run script with default parameters
      run: |
        python src/script_split.py tests/test.fastq.gz output_reads.fastq

    - name: Check output file
      run: |
        test -s output_reads.fastq && echo "Output file is not empty" || echo "Output file is empty"
